import psutil
import socket
import datetime


def generate_report():

    now = datetime.datetime.now()

    cpu = psutil.cpu_percent(interval=1)
    memory = psutil.virtual_memory().percent
    processes = len(psutil.pids())

    hostname = socket.gethostname()

    try:
        ip = socket.gethostbyname(hostname)
    except:
        ip = "Unknown"

    report = f"""
==============================
   JARVIS INCIDENT REPORT
==============================

Time: {now}

SYSTEM STATUS
-------------
CPU Usage      : {cpu} %
Memory Usage   : {memory} %
Processes      : {processes}

NETWORK INFO
------------
Hostname       : {hostname}
IP Address     : {ip}
"""
    report += "\nSECURITY FINDINGS\n"
    report += "------------------\n"

    if cpu > 80:
        report += "High CPU usage detected\n"
    if memory >80:
        report += "High memory usage detection\n"

    if cpu <= 80 and memory <= 80:
        report += "No critical threats detected. System operating within normal parameters. \n"
        report += "Overall Risk Level: LOW\n"

    report += f"Report Generated By: JARVIS-SOC\n"
    report += "\nEND OF REPORT\n"
    report += "-------------------------------\n"

    with open("incident_report.txt", "w") as f:
        f.write(report)

    print("\nReport generated: incident_report.txt\n")
